### ISSUE TITLE
undo capabilitiy in optimistic versioning environment

### ISSUE THREAD

**Issue by gebrits** [hoxton-one/deepstream.io#15]
What would be needed for making undo'ing commands work in deepstream?

**Comment by yasserf** [comment]
I'm afraid for performance (and most importantly memory consumption) reasons we only store the latest version of any record in deepstream. In order to implement undo you could however create a version history provider that stores a copy of every change and provides it on request.

```javascript
ds.record.listen( '*', function( recordName) {
    var rec = ds.record.getRecord( recordName );
    rec.subscribe(function(){
       //store the record version and reset it on request
    })
});

ds.rpc.provide( 'reset-record', function( data, response ){
// set the records value to the archived value
});
```
