### ISSUE TITLE
Want example for pushing a payload to specific users

### ISSUE THREAD

**Issue by bguiz** [hoxton-one/deepstream.io#18]
If deepstream supports this, I would like an example in the tutorials section to cover this use case:

- Say I have user A, connected to a server, and he emits an event with a payload.
- This payload is transformed on the server, and then 
- The payload is pushed to users B and C, who are both also connected to this server.

( also [asked on reddit](http://www.reddit.com/r/node/comments/39pxmf/deepstreamio_a_scalable_server_for_realtime_web/cs75x1u) )

**Comment by yasserf** [comment]
We recently added [a way to transform data on the server](http://deepstream.io/tutorials/transforming-data.html) before propagating it to other clients.

Please let us know if this satisfies your use case.

**Comment by yasserf** [comment]
Closing issue, feel free to reopen it if the data transforms didn't fit your usecase
