### ISSUE TITLE
Observables.

### ISSUE THREAD

**Issue by jimthedev** [hoxton-one/deepstream.io#28]
Hi there. Deepstream is really fantastic. I am curious if you'd ever considered using Rx.js and observables or at least adding some helper methods for people that would like to get an observable back instead of using callback and having to wrap then using Rx.js's .fromCallback method.? If not, no worries and thanks for the great framework.

**Comment by yasserf** [comment]
Hey Jim,

Thank you for the positive feedback! We already provide a similar tool for [knockout](https://github.com/hoxton-one/deepstream.io-tools-ko). 

We currently don't have much Rx.js experience, but if you would like to write a helper tool set to integrate with deepstream we would be more than happy to add it to our website download section!

Thanks!
