### ISSUE TITLE
deepstream.io-client-js: Should record.whenReady() really be private?

### ISSUE THREAD

**Issue by jwanglof** [hoxton-one/deepstream.io#36]
The JSDoc above `Record.prototype.whenReady` have the `@private`-tag. It doesn't make any difference when using the library but the documentation have the function listed ( http://deepstream.io/docs/record.html#whenReady( callback ) ) (btw, you should really fix the ancors so it's possible to link to them directly ;)) and my IDE (WebStorm if that matters) highlights every `whenReady()` usage since it's listed as private.

**Comment by yasserf** [comment]
Nope, that shouldn't have a private tag, thanks for finding the issue!

**Comment by yasserf** [comment]
Committed, will be in the next deepstream.io-client-js release.
