### ISSUE TITLE
Build two storage connectors

### ISSUE THREAD

**Issue by hoxton-one** [hoxton-one/deepstream.io#4]
Mongo Db and? Maybe couch? or cassandra?

**Comment by hoxton-one** [comment]
Actually...one of the Amazone Webservices ones might make more sense

Amazon DynamoDB
http://aws.amazon.com/dynamodb/?nc2=h_l3_db

**Comment by EnigmaCurry** [comment]
I have started a Cassandra connector here:

https://github.com/EnigmaCurry/deepstream.io-storage-cassandra
