### ISSUE TITLE
Is RPC's response.error() really implemented?

### ISSUE THREAD

**Issue by jwanglof** [hoxton-one/deepstream.io#40]
Every time I try to use the error-callback I get `undefined is not a function` and when looking in the `rpc-response.js`-file I don't see an error-function in the prototype.

I tried to implement my own error-function but when I send the ERROR-action it seems like the entire connection is disconnecting. The code I'm trying to use:
`this._connection.sendMsg( C.TOPIC.RPC, C.ACTIONS.ERROR, [ this._name, this._correlationId, typedData ] );`

Is there something I'm missing?

**Comment by yasserf** [comment]
We should have fixed this issue in release 0.2.18 for the client and also 0.4.1 of deepstream.

Can you confirm what version your using?

**Comment by jwanglof** [comment]
`deepstream.io-client-js`: 0.3.1
`deepstream.io`: 0.4.1

**Comment by yasserf** [comment]
Hmm, odd, 0.3.1 has the error on the prototype on the following line:

https://github.com/hoxton-one/deepstream.io-client-js/blob/0.3.1/src/rpc/rpc-response.js#l63
https://github.com/hoxton-one/deepstream.io-client-js/blob/0.3.1/dist/deepstream.js#l9130

Is it possible it could be a caching issue?

**Comment by jwanglof** [comment]
Sorry for late response, got some other tasks to do. The fault was at my end, sorry about that. I only looked on one server, which had the correct versions, but the other server didn't.
