### ISSUE TITLE
Do Deepstream check if the value of a message is the same as before?

### ISSUE THREAD

**Issue by jwanglof** [hoxton-one/deepstream.io#42]
Example code:
```
// Client A
var record = deepstream.record.getRecord('user/johan');
record.set('testValue', 1);
record.set('testValue', 1);

// Client B
var record = deepstream.record.getRecord('user/johan');
record.subscribe('testValue', function (newValue) {
    console.log('Value changed to: ' + newValue);
});
```

The subscription on client B will only be fired once even though the value is set twice. Is this some kind of implementation to check that the new value set to a record is different then the one that is already set?

**Comment by yasserf** [comment]
Yep, this saves unnecessary messages from being sent to the server / clients.

When would you need it to fire twice?

**Comment by jwanglof** [comment]
Our use-case would be if someone writes the same message twice. We have a snippet that our clients have a subscription on and changes as soon as a message is written. If this message is the same this subscription won't fire.

Where is this check done?
Maybe I can do a PR with an extra option that allows a message to be sent without the check

**Comment by yasserf** [comment]
Would it be possible to use a separate fields on the record that contains the last modified date ( or something that changes ) which will force subscriptions to run?

Another alternative would be to use an event saying that the record has changed.

```javascript
function update( record, path, value ) {
record.set('testValue', 1);
}

// Client A
var record = deepstream.record.getRecord('user/johan');
update( record, 'testValue', 1 );
update( record, 'testValue', 1 );

// Client B
var record = deepstream.record.getRecord('user/johan');
record.subscribe('testValue', function (newValue) {
    console.log('Value changed to: ' + newValue);
});
```

**Comment by yasserf** [comment]
Would it be possible to use a separate fields on the record that contains the last modified date ( or something that changes ) which will force subscriptions to run?

```javascript
function update( record, path, value ) {
    record.set('testValue', 1);
    record.set('lastModified', Date.now() )
}

// Client A
var record = deepstream.record.getRecord('user/johan');
update( record, 'testValue', 1 );
update( record, 'testValue', 1 );

// Client B
var record = deepstream.record.getRecord('user/johan');

function updated() {
    console.log('Value changed to: ' + record.getValue('testValue') );
}

record.subscribe('testValue', updated);
record.subscribe('lastModified', updated);
```

Another alternative would be to use an event saying that the record has changed.

```javascript
function update( record, path, value ) {
    if( record.get( 'testValue' ) === value ) {
         record.set('testValue', 1);
    } else {
         ds.event.emit( 'user/johan-updated' ); //needs better name!
    }
}

// Client A
var record = deepstream.record.getRecord('user/johan');
update( record, 'testValue', 1 );
update( record, 'testValue', 1 );

// Client B
var record = deepstream.record.getRecord('user/johan');
record.subscribe('testValue', function (newValue) {
    console.log('Value changed to: ' + newValue);
});
ds.event.subscribe(  'user/johan-updated' , function() {
  var value = record.getValue( 'testValue' )
} )
```

**Comment by jwanglof** [comment]
Yes, we have a timestamp-field that contains the last modified snippet-time which I'm using now as a "work-around", but I guess this works just fine as well =)

I was just curious if the original question was true or not. But would it be hard to implement a third argument to `record.set()`?
Some kind of force-change-event (or something).
I.e.:
```
var record = deepstream.record.getRecord('user/johan')
record.set('testValue', 1, true);
```

I realize this would be hard to implement on both PATCH and UPDATE.

**Comment by yasserf** [comment]
Just spoke with core team and we decided we won't accept any API changes for this since it conflicts with the core idea that a record is just a distributed state. So setting the same value multiple times doesn't actually change that.

But in answer to where it happens:

Sending things out should be easy ( remove a guard ):

https://github.com/hoxton-one/deepstream.io-client-js/blob/master/src/record/record.js#l101

Getting updates from server would be harder, since we currently only emit things that have changed, incase clientA updated the object and clientB only cared about certain paths.

https://github.com/hoxton-one/deepstream.io-client-js/blob/master/src/record/record.js#l460

I would personally recommend using the event approach as you shouldn't need to store any unrequired metadata to determine if something has changed to the same value.

**Comment by jwanglof** [comment]
Seems reasonable =)
Thanks for the answers, closing this issue as I think I got my question answered.
