### ISSUE TITLE
User management?

### ISSUE THREAD

**Issue by ricoberger** [hoxton-one/deepstream.io#45]
Hi, this is not an issue but a question.

How would you handle user registration? I have two ideas about this:

1. Use an Koa Server which handle user registration and login and then pass the user information to ```ds.login()```. Problem here is that I need two records one for the auth data and a second record which can observe with deepstream.
2. Use ```ds.login({user: anonymous, password: anonymous})``` when the user visit the page. So the user can create an record with his username and password and if the user login i would change ```ds.login()``` to ```ds.login({user: someusername, password: somepassword})```. The problem here is to allow the anonymous user the he can only create an user record.

What is the recommended way to achieve an user management system?

**Comment by WolframHempel** [comment]
Hi @ricoberger,

there are a number of approaches.

**The simplest one:** Use a http-server (e.g. Koa) to allow users to register and create credentials. Then, whenever a user logs in, request the user's data from within deepstream's permissionHandler's 'isValidUser' method.

**The most common one:** Token/Session based authentication. Use your KOA server to redirect users to a login-page and handle their login. If it is succesful, you return a session token in a cookie. On the actual application-page, the client read's the cookie (don't forget to set the cookie's httponly flag to false), sends it to deepstream and deepstream checks with your koa server if it's a valid session.
Session auth seems to be the most common way (we're using it as well) and there are plugins for pretty much every server, e.g. https://github.com/koajs/session for koa

Please let me know if that helps.

**Comment by ricoberger** [comment]
Hi @WolframHempel 

this was very helpful thank you

**Comment by WolframHempel** [comment]
cheers :-)
