### ISSUE TITLE
Login() doesn't work with TCP

### ISSUE THREAD

**Issue by Rajan** [hoxton-one/deepstream.io#58]
I'm using the same client/server code but it doesn't behave the same way in case of a TCP connection.

var DeepstreamServer = require( 'deepstream.io' ),
    server = new DeepstreamServer();

// Optionally you can specify some settings, a full list of which
// can be found here http://deepstream.io/docs/deepstream.html
server.set( 'host', 'localhost' );
server.set( 'port', 6020 );

// Set host and port for TCP connections
server.set( 'tcpHost', 'localhost' ); //default 0.0.0.0
server.set( 'tcpPort', 6021 ); //default 6021

server.set( 'permissionHandler', {
    isValidUser: function( handshakeData, authData, callback ) {
        console.log('auth now');
        if( authData.username === 'rajan' ) {

            callback( null, authData.username );
        } else {
            callback( 'Invalid user' );
        }

    },

    canPerformAction: function( username, message, callback ) {
        callback( null, true );
    }
});

// start the server
server.start();

Client HTML code below:

    <head>
        <script 
            type="text/javascript" 
            src="node_modules/deepstream.io-client-js/dist/deepstream.js">
        </script>
    </head>
    <body>
        <input type="text" />
        <script type="text/javascript">

            //ds = deepstream( 'localhost:6021' ).login();

            ds = deepstream( 'localhost:6020' ).login({
                username: 'rajan',
                password: 'sesame'
            }, function( success, errorCode, errorMessage ){
                //...
                console.log(success);
            });
            record = ds.record.getRecord( 'someUser' );
            input = document.querySelector( 'input' );

            input.onkeyup = function(){
                record.set( 'firstname', input.value );
            };

            record.subscribe( 'firstname', function( value ){
                input.value = value;
            });
        </script>
    </body>

The error it shows in browser console:

Uncaught Error: ACK_TIMEOUT: someUser (R)Client._$onError @ deepstream.js:6470RecordHandler._onRecordError @ deepstream.js:8408Emitter.emit @ deepstream.js:2549Record._onTimeout @ deepstream.js:8996setTimeout (async)Record @ deepstream.js:8482RecordHandler.getRecord @ deepstream.js:8266(anonymous function) @ index.html:23

Am I missing something or need to handle a situation?

**Comment by WolframHempel** [comment]
Browsers don't support TCP connections. Deepstream offers a TCP port for connections from NodeJS and going forward from other programming languages and WebSocket via engine.io for browsers.

**Comment by Rajan** [comment]
Thank you. I will get a Swift 2.0 TCP driver and see.
https://github.com/swiftsocket/SwiftSocket

**Comment by WolframHempel** [comment]
Cool, I think that makes sense
